# Generated by Django 3.2.4 on 2021-06-12 14:21

import datetime

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('email', models.EmailField(max_length=50, verbose_name='EMAIL')),
                ('mobile_no', models.CharField(max_length=20, verbose_name='PHONE NO.')),
                ('vehicle_year_make', models.CharField(max_length=4, verbose_name='VEHICLE YEAR MAKE')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='VEHICLE MODEL')),
                ('vehicle_no', models.CharField(max_length=50, verbose_name='VEHICLE NO.')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='DATE & TIME')),
                ('location', models.CharField(max_length=50, verbose_name='LOCATION')),
                ('type_of_loss', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Own Damage'), (2, 'Knock for Knock'), (3, 'Windscreen Damage'), (4, 'Theft')], max_length=7, verbose_name='TYPES OF LOSS')),
                ('description_loss', models.TextField(verbose_name='DESCRIPTION')),
                ('police_report_lodged', models.BooleanField(default=False, verbose_name='POLICE REPORT LODGED ?')),
                ('anybody_injured', models.BooleanField(default=False, verbose_name='ANYBODY INJURED ?')),
                ('photo', models.ImageField(upload_to='uploads/jpg', verbose_name='PHOTO')),
                ('cover_note', models.FileField(upload_to='uploads/pdf', verbose_name='INSURANCE COVER NOTE')),
                ('status', models.CharField(choices=[('In-Progress', 'In Progress'), ('Accepted', 'Accepted')], default='', max_length=20, verbose_name='NAME')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
