# Generated by Django 3.2.4 on 2021-06-13 09:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='DATE & TIME'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'In Progress'), ('Accepted', 'Accepted')], default='', max_length=20, verbose_name='STATUS'),
        ),
    ]
